#! /bin/bash
ip=$(ping -c1 biggay | grep -m1 -o -P '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}');
mkdir -p /mnt/samba
mount.cifs  //${ip}/biggay /mnt/samba -o username=raeaw,password=585305
chown raeaw -R /mnt/samba
chmod 777 -R /mnt/samba
exit
